"""add rejected flag

Revision ID: 0010
Revises: 0009
Create Date: 2026-06-28 07:05:39.526275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0010'
down_revision: Union[str, None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
        # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('rejected', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('pages', sa.Column('rejected_by', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'rejected_by')
    op.drop_column('pages', 'rejected')
    # ### end Alembic commands ###
