"""delete lines with events

Revision ID: 0011
Revises: 0010
Create Date: 2026-06-28 07:53:19.841367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0011'
down_revision: Union[str, None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('events_line_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'lines', ['line_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_line_id_fkey'), 'events', 'lines', ['line_id'], ['id'])
    # ### end Alembic commands ###
