"""line fks cascade delete

Revision ID: 0012
Revises: 0011
Create Date: 2026-06-28 08:00:39.549603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0012'
down_revision: Union[str, None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transcriptions_line_id_fkey'), 'transcriptions', type_='foreignkey')
    op.create_foreign_key(None, 'transcriptions', 'lines', ['line_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_user_progress_last_submitted_line_id'), 'user_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_progress', 'lines', ['last_submitted_line_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_progress_last_submitted_line_id'), 'user_progress', 'lines', ['last_submitted_line_id'], ['id'])
    op.drop_constraint(None, 'transcriptions', type_='foreignkey')
    op.create_foreign_key(op.f('transcriptions_line_id_fkey'), 'transcriptions', 'lines', ['line_id'], ['id'])
    # ### end Alembic commands ###
